version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  pre_build:
    commands:

  build:
    commands:

  post_build:
    commands:
      - aws cloudformation deploy --template-file template.yaml --stack-name stack-microfront --capabilities CAPABILITY_NAMED_IAM
      - echo "Deploying Microfront 1"
      - aws s3 sync ./front/microfront1 s3://MfBucket1 --delete
      - echo "Deploying Microfront 2"
      - aws s3 sync ./front/microfront2 s3://MfBucket2 --delete

artifacts:
  files:
    - template.yaml