AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Plantilla para desplegar microfrontends en S3

Resources:

  # S3 Bucket for Microfront 1
  MicrofrontBucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: unique-mfbucket1-12345
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      CorsConfiguration: 
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - "*"
            Id: MicrofrontBucket1CORS
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  MicrofrontBucket1Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MicrofrontBucket1
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::unique-mfbucket1-12345/*"
            Principal: "*"

  # S3 Bucket for Microfront 2
  MicrofrontBucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: unique-mfbucket2-12345
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      CorsConfiguration: 
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - "*"
            Id: MicrofrontBucket2CORS
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  MicrofrontBucket2Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MicrofrontBucket2
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::unique-mfbucket2-12345/*"
            Principal: "*"

Outputs:

  # Outputs for S3 Website URLs
  Microfront1URL:
    Description: "URL for Microfront 1"
    Value: !Sub "http://${MicrofrontBucket1}.s3-website-${AWS::Region}.amazonaws.com/"

  Microfront2URL:
    Description: "URL for Microfront 2"
    Value: !Sub "http://${MicrofrontBucket2}.s3-website-${AWS::Region}.amazonaws.com/"
